name: Keep Codespace Alive

on:
  schedule:
    - cron: "*/1 * * * *" # Every 5 minutes
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Send Ping to Codespace
        run: |
          curl -s --https://humble-memory-6jrjr9q9rg43rv59-8000.app.github.dev/ | head -n 1

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
