name: Keep ngrok Alive

on:
  schedule:
    - cron: "*/1 * * * *"  # Every 1 minute
  workflow_dispatch:  # Trigger manually if needed

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout your code

      - name: Install the latest ngrok version
        run: |
          # Download the latest ngrok version
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin/
          rm ngrok.zip

      - name: Authenticate ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}  # Use your secret token

      - name: Check ngrok installation
        run: ngrok version  # Verify ngrok version

      - name: Start ngrok tunnel
        run: |
          nohup ngrok tcp 25565 &  # Change the port if needed (e.g., 25565 for Minecraft)
          sleep 5  # Wait for ngrok to start

      - name: Get ngrok public URL
        run: |
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Ngrok URL: $NGROK_URL"

      - name: Send Ping to Ngrok Tunnel
        run: |
          # Ensure the ngrok URL is valid before making the curl request
          if [ -n "$NGROK_URL" ]; then
            curl -s $NGROK_URL | head -n 1
          else
            echo "Ngrok URL is not available."
          fi

      - name: Additional Actions
        run: |
          echo "Add other actions to build, test, and deploy your project."
